spring:
  application:
    name: kcmainmicro
  cloud:
    kubernetes:
      discovery:
        enabled: true
      reload:
        enabled: true
      config:
        name: kcmainmicro
logging:
  level:
    org.springframework.cloud.kubernetes: DEBUG