name: Deploy to ECR

on:
  push:
    branches:
      - main

env:
  ECR_REPOSITORY: kc-ecr

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

  - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11

  - name: Build with Maven
      run: mvn clean package -DskipTests

      - name: Build and push Docker image
        env:
  ECR_REGISTRY: 673380487826.dkr.ecr.eu-west-1.amazonaws.com
    run: |
      docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_SHA .
      docker login -u AWS -p ${{ secrets.AWS_ACCESS_KEY_ID }} https://$ECR_REGISTRY
      docker push $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_SHA